[package]
description = "Interact with unix processes/bash the same way as pexpect or Don libes expect does"
name        = "rexpect"
version     = "0.3.0"
authors     = ["Philipp Keller <philipp.keller@gmail.com>"]
repository  = "https://github.com/philippkeller/rexpect"
homepage    = "https://github.com/philippkeller/rexpect"
license     = "MIT"
categories  = ["os::unix-apis"]
keywords    = ["pty", "automation", "testing", "expect", "pexpect"]
readme      = "README.md"



[dependencies]
nix = "0.9"
regex = "0.2"
error-chain = "0.11"
tempfile = "2"

[badges]
travis-ci = { repository = "philippkeller/rexpect" }